/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SomnRequestBody { 
    jobId: string;
    user_email: string;
    reactant_pair_name: string;
    el: string;
    el_name: string;
    nuc: string;
    nuc_name: string;
}

