# Defines the deployment of the app running in a pod on any worker node
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: clean-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clean-frontend
  template:
    metadata:
      labels:
        app: clean-frontend
    spec:
      containers:
        - name: clean-frontend
          image: {{ .Values.controller.image }}

          env:
          - name: JOB_MANAGER_API_HOSTNAME
            value: {{ .Values.config.hostname | quote }}
          - name: JOB_MANAGER_API_BASEPATH
            value: {{ .Values.config.basePath | quote }}
          - name: OAUTH_SIGNIN_URL
            value: {{ .Values.config.signInUrl | quote }}
          - name: OAUTH_SIGNOUT_URL
            value: {{ .Values.config.signOutUrl | quote }}
          - name: OAUTH_USERINFO_URL
            value: {{ .Values.config.userInfoUrl | quote }}


          ports:
            - containerPort: 80
          imagePullPolicy: Always
